navbar:
  one:
    enabled: true
    type: GRASS_BLOCK
    name: §2Survival §c(Private)
    skullowner: nothing
    x: -10.5
    y: 11
    z: 17.5
    yaw: 90
    pitch: 0
    cmd: nothing
    server: ps
    port: 40410
    right: server
    left: teleport
  two:
    enabled: false
    type: nothing
    name: nothing
    skullowner: nothing
    x: 0
    y: 0
    z: 0
    yaw: 0
    pitch: 0
    cmd: nothing
    server: nothing
    port: 0
    right: nothing
    left: nothing
  three:
    enabled: true
    type: BEDROCK
    name: §bSpawn
    skullowner: nothing
    x: 8.5
    y: 11
    z: 17.5
    yaw: 90
    pitch: 0
    cmd: nothing
    server: nothing
    port: 0
    right: teleport
    left: teleport
  four:
    enabled: false
    type: nothing
    name: nothing
    skullowner: nothing
    x: 0
    y: 0
    z: 0
    yaw: 0
    pitch: 0
    cmd: nothing
    server: nothing
    port: 0
    right: nothing
    left: nothing
  five:
    enabled: false
    type: nothing
    name: nothing
    skullowner: nothing
    x: 0
    y: 0
    z: 0
    yaw: 0
    pitch: 0
    cmd: nothing
    server: nothing
    port: 0
    right: nothing
    left: nothing
  six:
    enabled: true
    type: BLAZE_POWDER
    name: §0Morph
    skullowner: nothing
    x: 0
    y: 0
    z: 0
    yaw: 0
    pitch: 0
    cmd: morph
    server: nothing
    port: 0
    right: cmd
    left: cmd
  seven:
    enabled: true
    type: COMMAND_BLOCK
    name: §4Test
    skullowner: nothing
    x: 8.5
    y: 11
    z: 35.5
    yaw: 0
    pitch: 0
    cmd: nothing
    server: test
    port: 2400
    right: server
    left: teleport
  eight:
    enabled: false
    type: nothing
    name: nothing
    skullowner: nothing
    x: 0
    y: 0
    z: 0
    yaw: 0
    pitch: 0
    cmd: nothing
    server: nothing
    port: 0
    right: nothing
    left: nothing
  nine:
    enabled: true
    type: BOOKSHELF
    name: §ea24 §c(Private)
    skullowner: nothing
    x: 8.5
    y: 11
    z: 2.5
    yaw: -180
    pitch: 0
    cmd: nothing
    server: a24
    port: 24000
    right: server
    left: teleport
  offline:
    type: BARRIER
    name: §4OFFLINE
    skullowner: nothing
settings:
  serverip: localhost
  effect:
    type: NIGHT_VISION
    duration: 99999
    amplifier: 255
    particle: false
  cooldown: 50
  sounds:
    teleport: ENTITY_ENDERMAN_TELEPORT
    connect1: ENTITY_EXPERIENCE_ORB_PICKUP
    connect2: ENTITY_PLAYER_LEVELUP
  spawn:
    x: 8.5
    y: 11
    z: 17.5
    yaw: 90
    pitch: 0
  message:
    connect: Verbinde zu %server%
