name: Build with Maven

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 16
      uses: actions/setup-java@v3
      with:
        java-version: '16'
        distribution: 'temurin'
        cache: maven

    - name: Read .version file
      id: version
      run: echo "::set-output name=version::$(cat .github/.version)"

    - name: Build with Maven
      run: | 
       sed -i 's/0.0.0/${{ steps.version.outputs.version }}/g' pom.xml
       grep pom.xml -e ${{ steps.version.outputs.version }}
       mvn -B package --file pom.xml
       rm -rf target/original-*.jar

    - uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: |
          target/sancraft-lobby*.jar

    - uses: "marvinpinto/action-automatic-releases@latest"
      if: github.event_name != 'pull_request'
      with:
        prerelease: ${{ github.ref != 'refs/heads/stable' }}
        repo_token: ${{ github.token }}
        title: ${{ steps.version.outputs.version }}
        automatic_release_tag: ${{ steps.version.outputs.version }}
        files: |
          target/sancraft-lobby*.jar
